dotenv:
  directory: ..
  ignore-if-missing: true

server:
  port: ${SERVER_PORT:8080}

fabric:
  samplesDir: ${FABRIC_SAMPLES_DIR:/home/wardiusz/Desktop/Projects/INZYNIERKA/AirportBlockchain/network/fabric-samples}
  usersDir: ${fabric.cryptoPath}/users
  channel: ${FABRIC_CHANNEL:airportchannel}
  chaincode: ${FABRIC_CHAINCODE:airport-cc}

  # Ścieżki do certyfikatów Org1 (budowane na podstawie samplesDir)
  mspId: Org1MSP
  cryptoPath: ${fabric.samplesDir}/test-network/organizations/peerOrganizations/org1.example.com
#  certPath: ${fabric.cryptoPath}/users/User1@org1.example.com/msp/signcerts/cert.pem
#  keyPath: ${fabric.cryptoPath}/users/User1@org1.example.com/msp/keystore
  tlsCertPath: ${fabric.cryptoPath}/peers/peer0.org1.example.com/tls/ca.crt

  # Adres peera
  peerEndpoint: localhost:7051
  peerHostname: peer0.org1.example.com

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 28800000 # 8h